pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy to Floci S3') {
            steps {
                dir('frontend') {
                    sh '''
                        aws s3 sync dist/ s3://smart-task-frontend/ \
                        --delete \
                        --endpoint-url http://localhost:4566
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Frontend deployment successful!'
        }

        failure {
            echo 'Frontend deployment failed!'
        }
    }
}
